version: '3'

services:

  broker:
    build:
      context: ./../broker
      dockerfile: ./../broker/broker.dockerfile
    restart: always
    ports: 
      - "8080:8080"
    deploy:
      mode: replicated
      replicas: 1

  authentication:
    build:
      context: ./../authentication
      dockerfile: ./../authentication/authentication.dockerfile
    restart: always
    ports:
      - "8082:8082"
    deploy: 
      mode: replicated
      replicas: 1
    environment:
      DSN: "host=postgres port=5432 user=postgres password=password dbname=users sslmode=disable timezone=UTC connect_timeout=5"


  postgres:
    image: 'postgres:14.2'
    ports:
      - "9432:5432"
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: users
    volumes:
      - ./db-data/postgres/:/var/lib/postgresql/data/